menu.add_slider_int("R8 Hitchance", 0, 100 )
menu.add_slider_int("R8 Dt hitchance", 0, 100 )
menu.add_slider_int("R8 Mindamage", 0, 120 )
menu.add_slider_int("R8 Force Dmg", 0, 120 )
menu.add_combo_box("R8 Baim",{"None","Prefer","Force"})
menu.add_check_box("R8 Teleport")
menu.add_check_box("R8 Auto stop")
menu.add_check_box("R8 Force accuracy")
menu.add_check_box("R8 Move Between Shots")
menu.add_check_box("R8 Early")
menu.add_check_box("R8 Point scale")
menu.add_slider_int("R8 Point scale Head", 0, 120 )
menu.add_slider_int("R8 Point scale Body", 0, 120 )
local r8mem = true
client.add_callback( "create_move" , function()
    local localplayer = entitylist.get_local_player()
end)